reshim.web/Areas/Admin/Controllers/LessonController.cs
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using reshim.data.commandProcessor.Dispatcher;
using reshim.domain.Commands.Content;
using reshim.domain.Queryies.Content.Lesson;
using reshim.domain.StrategiesFetch;
using reshim.model.view.ViewModels.Content.Lesson;

namespace reshim.web.Areas.Admin.Controllers
{
    public class LessonController : BaseController
    {
        public LessonController(ICommandBus commandBus, IQueryService queryService)
            : base(commandBus, queryService)
        {
        }

        #region category
        public ActionResult Categories(int? page, int? parentId, int? categoryId)
        {
            int p = page ?? 1;
            if (!parentId.HasValue)
            {
                var categories = QueryService.ExecuteQuery(new GetTopCategoriesLessons()
                {
                    Count = CountRecord,
                    Page = p
                });
                return View(new CategoriesLessonsViewModel()
                {
                    Categories = categories,
                    CategoryId = categoryId
                });
            }
            else
            {
                var categories = QueryService.ExecuteQuery(new GetChildrenCategoriesLessons()
                {
                    Count = CountRecord,
                    Page = p,
                    ParentId = parentId.Value
                });

                var parentCategory = QueryService.ExecuteQuery(new GetCategoryLessonsById() { Id = parentId.Value }); 

                return View(new CategoriesLessonsViewModel()
                {
                    Categories = categories,
                    CategoryId = categoryId,
                    ParentId = parentId,
                    Parent = parentCategory
                });
            }
        }


        [ChildActionOnly]
        public ActionResult CreateOrUpdateCategoryPartial(int? categoryId, int? parentId)
        {
            if (categoryId.HasValue)
            {
                var category = QueryService.ExecuteQuery(new GetCategoryLessonsById()
                {
                    Id = categoryId.Value,
                    IncludeProperties = new CategoryLessonWithParentFetchStrategy()
                });
                return View("~/Areas/Admin/Views/Lesson/_CreateOrUpdateCategory.cshtml", new CategoryLessonsFormModel()
                {
                    Id = category.Id,
                    Name = category.Name,
                    ParentId = category.ParentId,
                    Parent = category.Parent
                });
            }

            if (parentId.HasValue)
            {
                var parentCategory = QueryService.ExecuteQuery(new GetCategoryLessonsById()
                {
                    Id = parentId.Value,
                });

                return View("~/Areas/Admin/Views/Lesson/_CreateOrUpdateCategory.cshtml", new CategoryLessonsFormModel()
                {
                    ParentId = parentId,
                    Parent = parentCategory
                });
            }

            return View("~/Areas/Admin/Views/Lesson/_CreateOrUpdateCategory.cshtml", new CategoryLessonsFormModel());

        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult CreateOrUpdateCategory(CategoryLessonsFormModel model)
        {
            if (ModelState.IsValid)
            {
                var command = Mapper.Map<CategoryLessonsFormModel, CreateOrEditCategoryLessonCommand>(model);

                var result = CommandBus.Submit(command);
                if (result.Success)
                {
                    Success(string.Format("Категория для уроков \"{0}\" успешно {1}!", model.Name, model.Id.HasValue ? "обновлена" : "добавлена"));
                    return RedirectToAction("Categories", new { parentId = command.ParentId });
                }
                Error(string.Format("Произошла ошибка добавления категории для статей!"));

            }

            return View(model);
        }
        #endregion

        #region name lesson
        public ActionResult NamesLessons(int? page, int? nameLessonId)
        {
            int p = page ?? 1;
            var namesLessons = QueryService.ExecuteQuery(new GetNamesLessons()
            {
                Count = CountRecord,
                Page = p
            });



            return View(new NamesLessonsViewModel()
            {
                NameLessonId = nameLessonId,
                NamesLessons = namesLessons
            });
        }


        [ChildActionOnly]
        public ActionResult CreateOrUpdateNameLessonPartial(int? nameLessonId)
        {
            var categories = QueryService.ExecuteQuery(new GetAllTopCategoriesLessons());

            var flatCategories = QueryService.ExecuteQuery(new GetFlatLessonCategories()
            {
                Categories = categories
            });

            if (nameLessonId.HasValue)
            {
                var nameLessons = QueryService.ExecuteQuery(new GetNameLessonsById() { Id = nameLessonId.Value });
                return View("~/Areas/Admin/Views/Lesson/_CreateOrUpdateNameLesson.cshtml", new NameLessonsFormModel()
                {
                    Id = nameLessons.Id,
                    Name = nameLessons.Name,
                    CategoryId = nameLessons.CategoryId,
                    Categories = flatCategories
                });
            }

            return View("~/Areas/Admin/Views/Lesson/_CreateOrUpdateNameLesson.cshtml", new NameLessonsFormModel()
            {
                Categories = flatCategories
            });
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult CreateOrUpdateNameLesson(NameLessonsFormModel model)
        {
            if (ModelState.IsValid)
            {
                var command = Mapper.Map<NameLessonsFormModel, CreateOrEditNameLessonCommand>(model);

                var result = CommandBus.Submit(command);
                if (result.Success)
                {
                    Success(string.Format("Название цикла уроков \"{0}\" успешно {1}!", model.Name, model.Id.HasValue ? "обновлена" : "добавлена"));
                    return RedirectToAction("NamesLessons");
                }
                Error(string.Format("Произошла ошибка добавления цикла уроков!"));

            }

            return View(model);
        }
        #endregion

        #region chapters
        public ActionResult Chapters(int nameLessonId, int? page, int? chapterId)
        {
            int p = page ?? 1;
            var chapters = QueryService.ExecuteQuery(new GetChapters()
            {
                Count = CountRecord,
                Page = p,
                NameLessonId = nameLessonId
            });

            var nameLesson = QueryService.ExecuteQuery(new GetNameLessonsById(){ Id = nameLessonId });

            return View(new ChaptersViewModel()
            {
                ChapterId = chapterId,
                NameLessonId = nameLessonId,
                Chapters = chapters,
                NameLesson = nameLesson
            });
        }


        [ChildActionOnly]
        public ActionResult CreateOrUpdateChapterPartial(int nameLessonId, int? chapterId)
        {
            if (chapterId.HasValue)
            {
                var chapter = QueryService.ExecuteQuery(new GetChapterById() { Id = chapterId.Value });
                return View("~/Areas/Admin/Views/Lesson/_CreateOrUpdateChapter.cshtml", new ChapterFormModel()
                {
                    Id = chapter.Id,
                    Name = chapter.Name,
                    NameLessonId = chapter.NameLessonId
                });
            }

            return View("~/Areas/Admin/Views/Lesson/_CreateOrUpdateChapter.cshtml", new ChapterFormModel() { NameLessonId = nameLessonId });
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult CreateOrUpdateChapter(ChapterFormModel model)
        {
            if (ModelState.IsValid)
            {
                var command = Mapper.Map<ChapterFormModel, CreateOrEditChapterCommand>(model);

                var result = CommandBus.Submit(command);
                if (result.Success)
                {
                    Success(string.Format("Название главы \"{0}\" успешно {1}!", model.Name, model.Id.HasValue ? "обновлена" : "добавлена"));
                    return RedirectToAction("Chapters", new { nameLessonId = model.NameLessonId });
                }
                Error(string.Format("Произошла ошибка добавления главы для уроков!"));

            }

            return View(model);
        }
        #endregion

        #region lessons

        public ActionResult Lessons(int? page, int? nameLessonId, int? chapterId)
        {
            int p = page ?? 1;
            var nameLessons = QueryService.ExecuteQuery(new GetAllNamesLessons()).ToList();
            if (!nameLessonId.HasValue)
            {
                nameLessonId = nameLessons.First().Id;
            }

            var chapters = QueryService.ExecuteQuery(new GetAllChaptersByNameLessonId() { NameLessonId = nameLessonId.Value });

            var lessons = QueryService.ExecuteQuery(new GetLessons()
            {
                Count = CountRecord,
                Page = p,
                NameLessonId = nameLessonId,
                ChapterId = chapterId
            });

            return View(new LessonsViewModel()
            {
                Lessons = lessons,
                NamesLessons = nameLessons,
                NameLessonId = nameLessonId,
                Chapters = chapters,
                ChapterId = chapterId
            });
        }


        public ActionResult CreateOrUpdateLesson(int? id)
        {
            var namesLessons = QueryService.ExecuteQuery(new GetAllNamesLessons()).ToList();
            var nameLessonsId = namesLessons.First().Id;

reshim.web/Areas/Admin/Views/Lesson/Categories.cshtml
@using reshim.common.core.Pagination
@model reshim.model.view.ViewModels.Content.Lesson.CategoriesLessonsViewModel

@{
    ViewBag.Title = !Model.ParentId.HasValue ? "Категории" : string.Format("Категории \"{0}\"", Model.Parent.Name);
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@Html.Action("CreateOrUpdateCategoryPartial", "Lesson", new { categoryId = Model.CategoryId, parentId = Model.ParentId })

<div class="panel panel-default">
    <div class="panel-heading">
        <h6 class="panel-title">
            <strong class="label label-danger">@Model.Categories.TotalItemCount категории</strong>
        </h6>
    </div>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Название категории</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var category in Model.Categories)
                {
                    <tr id="@category.Id">
                        <td>@category.Id</td>
                        <td>
                            @if (!category.ParentId.HasValue)
                            {
                                @Html.ActionLink(category.Name, "Categories", "Lesson", new { parentId = category.Id, }, null)
                            }
                            else
                            {
                                @category.Name
                            }
                        </td>
                        <td>
                            <div class="table-controls">
                                <a href="@Url.Action("Categories", "Lesson", new { categoryId = category.Id, parentId = category.ParentId })" class="btn btn-default btn-icon btn-xs tip" title="" data-original-title="Редактировать"><i class="fa fa-plus-square"></i></a>
                                <a class="btn btn-default btn-icon btn-xs tip" title="" data-original-title="Удалить категорию" href="#delete" data-toggle="modal" data-id="@category.Id" data-name="@category.Name" data-text="@string.Format("Удалание категории \"{0}\".", category.Name)"><i class="fa fa-trash-o"></i></a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="table-footer">
        @Html.Pager(Model.Categories.PageSize, Model.Categories.PageNumber, Model.Categories.TotalItemCount)
    </div>
</div>

@Html.Partial("~/Areas/Admin/Views/Shared/Helpers/_DeleteContent.cshtml", Url.Action("Delete", "Lesson"))

reshim.web/Areas/Admin/Views/Lesson/Chapters.cshtml
@using reshim.common.core.Pagination
@model reshim.model.view.ViewModels.Content.Lesson.ChaptersViewModel

@{
    ViewBag.Title = string.Format("Главы раздела \"{0}\"", Model.NameLesson.Name);
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@Html.Action("CreateOrUpdateChapterPartial", "Lesson", new { chapterId = Model.ChapterId })

<input type="hidden" value="@Model.Chapters.PageNumber" name="curPage">
<div class="panel panel-default">
    <div class="panel-heading">
        <h6 class="panel-title">
            <strong class="label label-danger">@Model.Chapters.TotalItemCount уроков</strong>
        </h6>
    </div>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Название раздела</th>
                    <th>Позиция</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var chapter in Model.Chapters)
                {
                    <tr id="@chapter.Id">
                        <td>@chapter.Id</td>
                        <td>
                            @chapter.Name
                        </td>
                        <td class="position">
                            @chapter.Position
                        </td>
                        <td>
                            <div class="table-controls">
                                <a href="@Url.Action("Chapters", "Lesson", new { chapterId = chapter.Id, nameLessonId = Model.NameLessonId })" class="btn btn-default btn-icon btn-xs tip" title="" data-original-title="Редактировать"><i class="fa fa-plus-square"></i></a>
                                <a class="btn btn-default btn-icon btn-xs tip" title="" data-original-title="Удалить главу" href="#delete" data-toggle="modal" data-id="@chapter.Id" data-name="@chapter.Name" data-text="@string.Format("Удалание главы \"{0}\".", chapter.Name)"><i class="fa fa-trash-o"></i></a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="table-footer">
        @Html.Pager(Model.Chapters.PageSize, Model.Chapters.PageNumber, Model.Chapters.TotalItemCount).Options(x=>x.AddRouteValue("nameLessonId", Model.NameLessonId))
    </div>
</div>

@Html.Partial("~/Areas/Admin/Views/Shared/Helpers/_DeleteContent.cshtml", Url.Action("Delete", "Lesson"))

<script src="/Areas/Admin/Content/js/plugins/interface/jquery.rowsorter.min.js"></script>
<script src="/Areas/Admin/Content/js/admin/content/lesson-draggable.js"></script>

reshim.web/Areas/Admin/Views/Lesson/CreateOrUpdateLesson.cshtml
@model reshim.model.view.ViewModels.Content.Lesson.LessonFormModel

<link href="@Url.Content("~/Areas/Admin/Content/css/jquery.Jcrop.min.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Scripts/jquery.fileupload.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.iframe-transport.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Areas/Admin/Content/js/plugins/interface/jquery.Jcrop.min.js")" type="text/javascript"></script>

@{
    ViewBag.Title = Model.Id.HasValue ? "Редактирование урока" : "Создание урока";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("CreateOrUpdate", "Lesson", FormMethod.Post, new { @class = "form-horizontal validate", role = "form" }))
{
    @Html.HiddenFor(x => x.Id)
    <div class="panel panel-default">
        <div class="panel-heading">
            <h6 class="panel-title">@ViewBag.Title</h6>
        </div>
        <div class="panel-body">
            <div class="form-group">
                <label class="col-sm-2 control-label">Название урока: <span class="mandatory">*</span></label>
                <div class="col-sm-10">
                    @Html.TextBoxFor(x => x.Name, new { @class = "required form-control" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2 control-label">Заголовок урока (СЕО): <span class="mandatory">*</span></label>
                <div class="col-sm-10">
                    @Html.TextBoxFor(x => x.TitleSeo, new { @class = "required form-control" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2 control-label">Описание урока (СЕО): <span class="mandatory">*</span></label>
                <div class="col-sm-10">
                    @Html.TextAreaFor(x => x.DescriptionSeo, 5, 5, new { @class = "required form-control" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2 control-label">Ключевые урока (СЕО): <span class="mandatory">*</span></label>
                <div class="col-sm-10">
                    @Html.TextAreaFor(x => x.KeywordsSeo, 5, 5, new { @class = "required form-control" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2 control-label">Текст: <span class="mandatory">*</span></label>
                <div class="col-sm-10">
                    @Html.TextAreaFor(x => x.Text, 5, 5, new { @class = "required form-control editor" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2 control-label">Превью: <span class="mandatory">*</span></label>
                <div class="col-sm-10">
                    @Html.TextAreaFor(x => x.Preview, 5, 5, new { @class = "required form-control editor" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Цикл урока: <span class="mandatory">*</span></label>
                <div class="col-sm-10">
                    @Html.DropDownListFor(x => x.NameLessonId, Model.NamesLessons.Select(x => new SelectListItem() { Text = x.Name, Value = x.Id.ToString() }), new { @class = "select-search-names-lessons" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Раздел: </label>
                <div class="col-sm-10">
                    @Html.DropDownListFor(x => x.ChapterId, Model.Chapters.Select(x => new SelectListItem() { Text = x.Name, Value = x.Id.ToString() }), "Выберите раздел", new { @class = "select-search-chapters" })
                </div>
            </div>
            @Html.Partial("~/Areas/Admin/Views/Shared/Helpers/_CropImage.cshtml", string.IsNullOrEmpty(Model.Image) ? "" : Model.Image)


            <div class="form-actions text-right">
                <input type="submit" value="Сохранить" class="btn btn-primary">
            </div>

        </div>
    </div>
}

<script src="/Areas/Admin/Content/js/admin/helper.crop-image.js"></script>

<script>
    (function ($) {
        $(".validate").validate({
            onkeyup: true,
            errorPlacement: function (error, element) {
                error.insertAfter(element);
            },
            rules: {
                Name: {
                    required: true
                },
                TitleSeo: {
                    required: true
                },
                DescriptionSeo: {
                    required: true
                },
                KeywordsSeo: {
                    required: true
                },
                Text: {
                    required: true
                },
                Preview: {
                    required: true
                }
            },
            success: function (label) {
                label.text('Успешно!').addClass('valid');
            }
        });

        // ddl
        var namesLessons = $(".select-search-names-lessons");
        var chapters = $(".select-search-chapters");
        
        namesLessons.select2({
            width: 400
        });
        
        chapters.select2({
            width: 400
        });

        namesLessons.bind("change keyup", function () {
            loadChapters(namesLessons.find("option:selected").val());
            namesLessons.fadeIn("slow");
        });


        function loadChapters(selectedItemNameLesson) {
            $.ajax({
                type: "POST",
                url: "/api/helper/getchapters/" + selectedItemNameLesson,
                success: function (data) {
                    changeChapters(data);
                }
            });
        }
        
        function changeChapters(data) {
           chapters.find("option").remove();
            chapters.append($("<option></option>").val("").html("Выберите раздел"));
            for (var i = 0; i < data.length; i++) {
                chapters.append($("<option></option>").val(data[i].Id).html(data[i].Name));
            }
            chapters.select2({
                width: 400
            });
        }



    })(jQuery);
</script>

reshim.web/Areas/Admin/Views/Lesson/Lessons.cshtml
@using reshim.common.core.Pagination
@model reshim.model.view.ViewModels.Content.Lesson.LessonsViewModel

@{
    ViewBag.Title = "Уроки";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<input type="hidden" value="@Model.Lessons.PageNumber" name="curPage">

<div class="container-fluid">
    <div class="page-header">
        <ul class="middle-nav left-nav">
            <li><a href="@Url.Action("CreateOrUpdateLesson", "Lesson", new { area = "admin" })" class="btn btn-default"><i class="fa fa-plus-square-o"></i><span>Создать урок</span></a></li>
        </ul>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h6 class="panel-title">Сортировка</h6>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm("Lessons", "Lesson", FormMethod.Get, new { @class = "form-horizontal" }))
        {
            <div class="form-group">
                <label class="col-sm-2 control-label">Цикл уроков</label>
                <div class="col-sm-10">
                    @Html.DropDownListFor(x => x.NameLessonId, Model.NamesLessons.Select(x => new SelectListItem() { Text = x.Name, Value = x.Id.ToString() }), new { @class = "select-search-names-lessons" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Разделы</label>
                <div class="col-sm-10">
                    @Html.DropDownListFor(x => x.ChapterId, Model.Chapters.Select(x => new SelectListItem() { Text = x.Name, Value = x.Id.ToString() }), "Выберите раздел" , new { @class = "select-search-chapters" })
                </div>
            </div>
            <div class="form-actions text-right">
                <input type="submit" value="Применить" class="btn btn-primary">
            </div>
        }
    </div>
</div>


<div class="panel panel-default">
    <div class="panel-heading">
        <h6 class="panel-title">
            <strong class="label label-danger">@Model.Lessons.TotalItemCount уроков</strong>
        </h6>
    </div>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Картинка</th>
                    <th>Название урока</th>
                    <th>Позиция</th>
                    <th>Дата создания</th>
                    <th>Дата обновления</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var lesson in Model.Lessons)
                {
                    <tr id="@lesson.Id" class="draggable">
                        <td>@lesson.Id</td>
                        <td><img class="miniature" src="@lesson.Image" /></td>
                        <td>@lesson.Name</td>
                        <td class="position">@lesson.Position</td>
                        <td>@lesson.DateCreate</td>
                        <td>@lesson.DateUpdate</td>
                        <td>
                            <div class="table-controls">
                                <a href="@Url.Action("CreateOrUpdateLesson", "Lesson", new { id = lesson.Id })" class="btn btn-default btn-icon btn-xs tip" title="" data-original-title="Редактировать"><i class="fa fa-pencil"></i></a>
                                <a class="btn btn-default btn-icon btn-xs tip" title="" data-original-title="Удалить статью" href="#delete" data-toggle="modal" data-id="@lesson.Id" data-name="@lesson.Name" data-text="@string.Format("Удалание  урока \"{0}\".", lesson.Name)"><i class="fa fa-trash-o"></i></a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="table-footer">
        @Html.Pager(Model.Lessons.PageSize, Model.Lessons.PageNumber, Model.Lessons.TotalItemCount).Options(x => x.Action("Lessons").AddRouteValue("nameLessonId", Model.NameLessonId).AddRouteValue("chapterId", Model.ChapterId))
    </div>
</div>

@Html.Partial("~/Areas/Admin/Views/Shared/Helpers/_DeleteContent.cshtml", Url.Action("Delete", "Lesson"))

<script src="/Areas/Admin/Content/js/plugins/interface/jquery.rowsorter.min.js"></script>
<script src="/Areas/Admin/Content/js/admin/content/lesson-draggable.js"></script>


<script>
    (function ($) {
        var namesLessons = $(".select-search-names-lessons");
        var chapters = $(".select-search-chapters");

        namesLessons.select2({
            width: 400
        });

        chapters.select2({
            width: 400
        });

        namesLessons.bind("change keyup", function () {
            loadChapters(namesLessons.find("option:selected").val());
            namesLessons.fadeIn("slow");
        });


        function loadChapters(selectedItemNameLesson) {
            $.ajax({
                type: "POST",
                url: "/api/helper/getchapters/" + selectedItemNameLesson,
                success: function (data) {
                    changeChapters(data);
                }
            });
        }

        function changeChapters(data) {
            chapters.find("option").remove();
            chapters.append($("<option></option>").val("").html("Выберите раздел"));
            for (var i = 0; i < data.length; i++) {
                chapters.append($("<option></option>").val(data[i].Id).html(data[i].Name));
            }
            chapters.select2({
                width: 400
            });
        }
    })(jQuery);
</script>

reshim.web/Areas/Admin/Views/Lesson/NamesLessons.cshtml
@using reshim.common.core.Pagination
@model reshim.model.view.ViewModels.Content.Lesson.NamesLessonsViewModel

@{
    ViewBag.Title = "Циклы уроков";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@Html.Action("CreateOrUpdateNameLessonPartial", "Lesson", new { nameLessonId = Model.NameLessonId })

<div class="panel panel-default">
    <div class="panel-heading">
        <h6 class="panel-title">
            <strong class="label label-danger">@Model.NamesLessons.TotalItemCount уроков</strong>
        </h6>
    </div>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Название урока</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var nameLesson in Model.NamesLessons)
                {
                    <tr id="@nameLesson.Id">
                        <td>@nameLesson.Id</td>
                        <td>
                            @Html.ActionLink(nameLesson.Name, "Chapters", "Lesson", new { nameLessonId = nameLesson.Id }, null)
                        </td>
                        <td>
                            <div class="table-controls">
                                <a href="@Url.Action("NamesLessons", "Lesson", new { nameLessonId = nameLesson.Id })" class="btn btn-default btn-icon btn-xs tip" title="" data-original-title="Редактировать"><i class="fa fa-plus-square"></i></a>
                                <a class="btn btn-default btn-icon btn-xs tip" title="" data-original-title="Удалить цикл уроков" href="#delete" data-toggle="modal" data-id="@nameLesson.Id" data-name="@nameLesson.Name" data-text="@string.Format("Удалание цикла уроков \"{0}\".", nameLesson.Name)"><i class="fa fa-trash-o"></i></a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="table-footer">
        @Html.Pager(Model.NamesLessons.PageSize, Model.NamesLessons.PageNumber, Model.NamesLessons.TotalItemCount)
    </div>
</div>

@Html.Partial("~/Areas/Admin/Views/Shared/Helpers/_DeleteContent.cshtml", Url.Action("Delete", "Lesson"))

reshim.web/Areas/Admin/Views/Lesson/_CreateOrUpdateCategory.cshtml
@model reshim.model.view.ViewModels.Content.Lesson.CategoryLessonsFormModel

@using (Html.BeginForm("CreateOrUpdateCategory", "Lesson", FormMethod.Post, new { @class = "form-horizontal validate", role = "form" }))
{
    @Html.HiddenFor(x => x.Id)
    @Html.HiddenFor(x => x.ParentId)
    <div class="panel panel-default">
        <div class="panel-heading">
            <h6 class="panel-title">
                @(Model.Id.HasValue ? string.Format("Редактирование категории \"{0}\"", Model.Name) :
                string.Format("{0}", !Model.ParentId.HasValue ? "Добавление категории" : "Добавление категории в \"" + Model.Parent.Name + "\""))
            </h6>
        </div>
        <div class="panel-body">
            <div class="form-group">
                <label class="col-sm-2 control-label">Название категории: <span class="mandatory">*</span></label>
                <div class="col-sm-10">
                    @Html.TextBoxFor(x => x.Name, new { @class= "required form-control" })
                </div>
            </div>
            <div class="form-actions text-right">
                <input type="submit" value="Сохранить" class="btn btn-primary">
            </div>

        </div>
    </div>
}

<script>
    (function ($) {
        $(".validate").validate({
            onkeyup: true,
            errorPlacement: function (error, element) {
                error.insertAfter(element);
            },
            rules: {
                Name: {
                    required: true
                }
            },
            success: function (label) {
                label.text('Успешно!').addClass('valid');
            }
        });
    })(jQuery);
</script>