reshim.web/Areas/Admin/Controllers/TaskController.cs
using System.Web.Mvc;
using reshim.data.commandProcessor.Dispatcher;
using reshim.domain.Queryies.Task;
using reshim.domain.StrategiesFetch;
using reshim.model.Entities;
using reshim.web.Helpers;

namespace reshim.web.Areas.Admin.Controllers
{
    [Access(new[] { UserRoles.Admin })]
    public class TaskController : BaseController
    {
        public TaskController(ICommandBus commandBus, IQueryService queryService)
            : base(commandBus, queryService)
        {
        }

        public ActionResult DetailTask(int id)
        {
            var taskView = QueryService.ExecuteQuery(new GetTaskById()
            {
                Id = id,
                IncludeProperties = new TaskFetchStrategyNumber1()
            });
            return View(taskView);
        }
    }
}

reshim.web/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using MassTransit;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using reshim.data.commandProcessor.Dispatcher;
using reshim.common;
using reshim.databus.model.contracts.Contracts.Alerts;
using reshim.domain.Commands.Profile;
using reshim.domain.Commands.Security;
using reshim.domain.Commands.Task;
using reshim.domain.Queryies.User;
using reshim.model.view.ViewModels.Auth;
using reshim.model.view.ViewModels.Task;
using reshim.oauth2;
using reshim.oauth2.Client;
using reshim.web.core.Auth;
using reshim.web.core.Model;
using reshim.web.Helpers;

namespace reshim.web.Controllers
{
    public class AuthController : BaseController
    {
        private readonly ICommandBus _commandBus;
        private readonly IQueryService _queryService;
        private readonly IFormsAuthentication _formAuthentication;
        private readonly IBus _bus;
        private readonly AuthorizationRoot _authorizationRoot = new AuthorizationRoot();

        public AuthController(ICommandBus commandBus, IQueryService queryService, IBus bus, IFormsAuthentication formAuthentication)
        {
            _commandBus = commandBus;
            _queryService = queryService;
            _bus = bus;
            _formAuthentication = formAuthentication;
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult ForgotPassword(string token, string login)
        {
            var model = new ConfirmForgotPasswordViewModel()
            {
                Errors = new List<ValidationResult>()
            };

            var user = _queryService.ExecuteQuery(new GetUserByLogin() { Login = login });

            if (user == null)
            {
                model.Errors.Add(new ValidationResult("", "Данного пользователя не существует."));
                return View(model);
            }

            model.Errors.AddRange(_commandBus.Validate(new CanUpdatePasswordValidation()
            {
                Email = user.Email,
                Login = user.Login,
                Token = token
            }));

            model.EmailOrLogin = user.Email;
            model.UserId = user.UserId;
            return View(model);
        }

        [HttpGet]
        public ActionResult Logout()
        {
            _commandBus.Submit(new UserLogoutCommand());
            return RedirectToAction("Index", "Home");
        }


        #region регистрация через социальные сети
        private const string ProviderNameKey = "RESHIM";

        private string ProviderName
        {
            get
            {
                var value = (string)Session[ProviderNameKey];
                if (string.IsNullOrEmpty(value))
                    return ProviderNameKey;
                return value;

            }
            set { Session[ProviderNameKey] = value; }
        }

        private IClient GetClient()
        {
            return _authorizationRoot.Clients.First(c => c.ProviderName.ToLower() == ProviderName.ToLower());
        }

        [HttpGet] // 1 step
        public ActionResult RegisterFromService(string providerName)
        {
            ProviderName = providerName;
            return new RedirectResult(GetClient().GetLoginLinkUri());
        }

        [HttpGet] // 2 step
        public ActionResult ConfirmRegisterFromService()
        {
            HttpCookie cookieTask = Request.Cookies["task"];

            var model = new ConfirmRegisterFromServiceViewModel();
            model.RedirectUrl = SiteUrl;

            var userInfo = GetClient().GetUserInfo(Request.QueryString);


            var isUser = _queryService.ExecuteQuery(new GetUserByIdService() { IdService = userInfo.Id });

            if (isUser != null) // auth
            {
                _formAuthentication.SetAuthCookie(HttpContext, UserAuthenticationTicketBuilder.CreateAuthenticationTicket(isUser));
                if (IsValidCookies(cookieTask))
                {
                    var obj = JsonConvert.DeserializeObject<CreateTaskFormModel>(cookieTask.Value, new IsoDateTimeConverter { DateTimeFormat = "dd/MM/yyyy" });
                    var command = Mapper.Map<CreateTaskFormModel, CreateTaskCommand>(obj);
                    command.CustomerId = isUser.UserId;

                    var errors = _commandBus.Validate(command).ToList();

                    if (!errors.Any())
                    {
                        var result = _commandBus.Submit(command);
                        if (result.Success)
                        {
                            if (IsValidCookies(cookieTask))
                            {
                                DeleteCookie("task");
                                SetFlagCookie("IsConfirmCreateTask");
                            }
                        }
                    }
                }
                return View(model);

            }
            else // register
            {
                var fullPath = userInfo.PhotoUri.SaveFile("Profile");
                var command = new UserRegisterFromServiceCommand()
                {
                    FirstName = userInfo.FirstName,
                    LastName = userInfo.LastName,
                    IdService = userInfo.Id,
                    Service = (int)Enum.Parse(typeof(Service), ProviderName),
                    UrlVk = userInfo.Id,
                    UpdatePhoto = new UpdatePhotoCommand()
                    {
                        Path = fullPath
                    },
                    CreateTask = IsValidCookies(cookieTask) ?
                    Mapper.Map<CreateTaskFormModel, CreateTaskCommand>(JsonConvert.DeserializeObject<CreateTaskFormModel>(cookieTask.Value, new IsoDateTimeConverter { DateTimeFormat = "dd/MM/yyyy" }))
                    :
                    null
                };

                var result = _commandBus.Submit(command);
                if (result.Success)
                {
                    if (IsValidCookies(cookieTask))
                    {
                        _bus.Publish(new AlertNewTask(result.LastId, SiteUrl));
                        DeleteCookie("task");
                        SetFlagCookie("IsConfirmCreateTask");
                    }

                    var newUser = _queryService.ExecuteQuery(new GetUserByIdService() { IdService = userInfo.Id });
                    _formAuthentication.SetAuthCookie(HttpContext, UserAuthenticationTicketBuilder.CreateAuthenticationTicket(newUser));
                    return View(model);
                }

                SetFlagCookie("IsPopunFailRegistration");
                return View(model);
            }
        }
        #endregion
    }
}

reshim.web/Controllers/BillingController.cs
using System.Web.Mvc;
using reshim.data.commandProcessor.Dispatcher;
using reshim.common.Attributes;
using reshim.common.core.Extensions;
using reshim.domain.Queryies.Billing;
using reshim.model.Entities;
using reshim.model.view.ViewModels.Billing;
using reshim.web.Helpers.Binders;

namespace reshim.web.Controllers
{
    [Authorize]
    public class BillingController : BaseController
    {
        private readonly IQueryService _queryService;
        
        public BillingController(IQueryService queryService)
        {
            _queryService = queryService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PaymentForm(PaywayVia payway)
        {
            return View(payway);
        }

        public ActionResult WithdrawalForm()
        {
            var model = new WithdrawalFormModel
            {
                TypePayments = EnumEx.GetKeyValue<PaywayVia, EnableWithdrawalAttribute, NameAttribute, TypeAttribute>()
            };
            return View(model);
        }

        public ActionResult HistoryPayments(int? page)
        {
            int p = page ?? 1;
            var invocesView = _queryService.ExecuteQuery(new GetPaymentsByUserId() { Count = CountRecord, Page = p, UserId = User.UserId });
            return View(invocesView);
        }

        public ActionResult HistoryWithdrawels(int? page)
        {
            int p = page ?? 1;
            var withdrawalsView = _queryService.ExecuteQuery(new GetWithdrawelsByUserId() { Count = CountRecord, Page = p, UserId = User.UserId });
            return View(withdrawalsView);
        }

        public ActionResult HistoryInternalPayments(int? page)
        {
            int p = page ?? 1;
            var paymentsView = _queryService.ExecuteQuery(new GetInternalPaymentsByUserId() { Count = CountRecord, Page = p, UserId = User.UserId });
            return View(paymentsView);
        }

        [HttpPost]
        public ActionResult Success([ModelBinder(typeof(InterkassaSuccesOrFailBinder))]ConfirmRequestInterkassaFormModel model)
        {
            var cookieTask = Request.Cookies["ComplitedTask"];
            model.HasCompletedTask = IsValidCookies(cookieTask);
            if (model.HasCompletedTask) DeleteCookie("ComplitedTask");
            return View(model);
        }

        [HttpPost]
        public ActionResult Fail([ModelBinder(typeof(InterkassaSuccesOrFailBinder))]ConfirmRequestInterkassaFormModel model)
        {
            return View(model);
        }
    }
}

reshim.web/Controllers/ChatController.cs
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using reshim.data.commandProcessor.Dispatcher;
using reshim.domain.Commands.Chat;
using reshim.domain.Queryies.Chat;
using reshim.model.view.ViewModels.Chat;

namespace reshim.web.Controllers
{
    [Authorize]
    public class ChatController : BaseController
    {
        private readonly IQueryService _queryService;
        private readonly ICommandBus _commandBus;

        public ChatController(IQueryService queryService, ICommandBus commandBus)
        {
            _queryService = queryService;
            _commandBus = commandBus;
        }

        public ActionResult Index()
        {
            var dialogues = _queryService.ExecuteQuery(new GetDialoguesByUserId() { UserId = User.UserId });
            return View(dialogues);
        }

        public ActionResult Dialog(int? dialogId, int? userId)
        {
            if (dialogId.HasValue)
            {
                _commandBus.Submit(new ReadAllMessagesCommand() { DialogId = dialogId.Value, UserId = User.UserId });
                var chatView = _queryService.ExecuteQuery(new GetMessagesByDialogId() { DialogId = dialogId.Value, Page = 1, Count = 10 });
                if (chatView.User1Id != User.UserId && chatView.User2Id != User.UserId) throw new HttpException(403, "Данный ресур не может быть просмотрен.");
                return View(chatView);
            }
            else if (userId.HasValue)
            {
                var isDialog = _queryService.ExecuteQuery(new IsDialogById() { UserId1 = userId.Value, UserId2 = User.UserId });

                if (!isDialog)
                {
                    var result = _commandBus.Submit(new CreateDialogCommand() { RecipientId = userId.Value, SenderId = User.UserId });
                    return RedirectToAction("Dialog", new { dialogId = result.LastId });
                }

                var dialog = _queryService.ExecuteQuery(new GetDialogByUserIds()
                {
                    UserId1 = userId.Value, 
                    UserId2 = User.UserId
                }); 
                return RedirectToAction("Dialog", new { dialogId = dialog.Id });
            }

            return View(new ChatViewModel() { Messages = new List<MessageViewModel>() });
        }


    }

}

reshim.web/Controllers/UserController.cs
using System.Web.Mvc;
using reshim.data.commandProcessor.Dispatcher;
using reshim.domain.Queryies.Profile;
using reshim.domain.Queryies.User;
using reshim.domain.StrategiesFetch;

namespace reshim.web.Controllers
{
    [Authorize]
    public class UserController : BaseController
    {
        private readonly IQueryService _queryService;

        public UserController(IQueryService queryService)
        {
            this._queryService = queryService;
        }

        [AllowAnonymous]
        public ActionResult Index(int? id)
        {
            var userId = id ?? User.UserId;
            return View(userId);
        }

        [AllowAnonymous]
        public PartialViewResult ProfileUser(int id)
        {
            var userView = _queryService.ExecuteQuery(new GetUserById()
            {
                Id = id,
                IncludeProperties = new UserFetchStrategy()
            });
            return PartialView("Partials/_ProfileUser", userView);
        }

        public ActionResult Profile()
        {
            return View();
        }

        public PartialViewResult EditProfile()
        {
            var viewProfile = _queryService.ExecuteQuery(new GetProfileByUserId() { Id = User.UserId });
            return PartialView("Partials/_EditProfile", viewProfile);
        }

        public PartialViewResult EditPhoto()
        {
            var viewProfile = _queryService.ExecuteQuery(new GetUserById() { Id = User.UserId });
            return PartialView("Partials/_EditPhoto", viewProfile);
        }

        public ActionResult PersonalCabinet()
        {
            var model = _queryService.ExecuteQuery(new GetStatisticsTaskUser() { UserId = User.UserId });
            return View(model);
        }

    }
}

reshim.web/Views/Shared/Partials/AuthMenu.cshtml
@using reshim.web.core.Extensions
@model reshim.model.view.ViewModels.Home.AuthMenuViewModel

<div class="auth-photo column3">
    <div class="photo-container">
        <img class="photo-profile" src="@string.Format("{0}?w=90&h=90&mode=crop", Model.User.GetPhoto)" alt="@Model.User.Login" />
    </div>
    <a href="@Url.Action("Profile", "User")">@Model.User.Login</a>
</div>

<div class="auth-menu column5">
    <ul>
        <li data-link="@Url.Action("Logout", "Auth")">
            <div class="sprite-exit"></div>
            <p class="text">Выход</p>
        </li> 
        <li data-link="@Url.Action("PersonalCabinet", "User", new { @area = User.GetReshimUser().RoleName == "User" || User.GetReshimUser().RoleName == "Admin" ? "" : User.GetReshimUser().RoleName })">
            <div class="sprite-user"></div>
            <p class="text">Личный кабинет</p>
        </li>
        <li data-link="@(Url.Action("Index", "Billing", new { @area = "" }) + "#cash-in")">
            <div class="sprite-pay"></div>
            <p class="text">Балланс</p>
            <p id="PayValue">(@Model.User.PaymentData.Ballance RUR)</p>
        </li>
        <li data-link="@Url.Action("Index", "Chat")">
            <div class="sprite-mail"></div>
            <p class="text">Сообщений</p>
            <p class="CountAllNewMessage">(@Model.CountNewMessage)</p>
        </li>
    </ul>
</div>

reshim.web/Views/Shared/Partials/_Advantages.cshtml
<strong class="title">Почему мы? Это просто.</strong>
<ul>
    <li>
        <p class="frame">
            <strong>100%</strong>
        </p>
        <p class="desc">
            защита Вашего заказа и денег
        </p>
    </li>
    <li>
        <p class="frame">
            <strong>3</strong>
            <strong>часа</strong>
        </p>
        <p class="desc">
            минимальное время выполнения заказа
        </p>
    </li>
    <li>
        <p class="frame">
            <strong>15</strong>
            <strong>минут</strong>
        </p>
        <p class="desc">
            средняя время оценки заказа
        </p>
    </li>
    <li>
        <p class="frame">
            <strong>3</strong>
            <strong>года</strong>
        </p>
        <p class="desc">
            на рынке услуг
        </p>
    </li>
    <li>
        <p class="frame">
            <strong>24/7</strong>
        </p>
        <p class="desc">
            круглосуточная работа сервиса
        </p>
    </li>
</ul>

reshim.web/Views/Shared/Partials/_FilterTasks.cshtml
@using reshim.web.core.Extensions
@using (Html.BeginForm("Index", "Task", FormMethod.Get))
{
    <div class="filter">
        <div class="input-control select">
            <select name="status">
                <option value="">Все</option>
                @foreach (var type in Model.Status)
                {
                    <option value="@type.Value" selected="@(type.Value == Model.SelectedStatus)">@type.Key</option>
                }
            </select>
        </div>
        
        @if (User.GetReshimUser().IsAuthenticated)
        {
            <div id="MyTask" data-role="checkbox" data-checked="@Model.SelectedMyTask" data-name="isMyTask" data-caption="Только мои задачи"></div>
        }
        <button id="FilterBtn" class="green">Применить</button>
    </div>
}

reshim.web/Views/Shared/Partials/_LastTask.cshtml
@using reshim.web.Helpers
@model IEnumerable<reshim.model.view.ViewModels.Task.TaskViewModel>

<div class="wrapper">
    <div class="tasks">
        @Html.TextWithIco(SVGHelper.SubjectICO(), "Выполненные задания:", colorIco: "gray90")
        @foreach (var task in Model)
        {
            @Html.Partial("Partials/_Task", task)
        }
    </div>
    <a href="@Url.Action("Index", "Task")" class="btn green all-tasks">@Html.TextWithIco(SVGHelper.CircleDownICO(), "Все задания",  htmlAttributes: new { @class = "size_20" })</a>
</div>


 

reshim.web/Views/Shared/Partials/_MenuArticle.cshtml
@model List<reshim.model.view.ViewModels.Content.MenuItemModel>
<div class="wrapper-nav">
    <ul>
        <li class="first">Категории</li>
        @foreach (var cat in Model)
        {
            <li class="@(cat.SubMenu != null && cat.SubMenu.Any() ? "isSubCategories" : "")">
                <a href="@Url.Action("Articles", "Content", new { category = cat.Alias })" class="@(cat.SubMenu != null && cat.SubMenu.Any() ? "enable-icon" : "")">@cat.Text</a>
                @if (cat.SubMenu != null && cat.SubMenu.Any())
                {
                    <ul class="subCategories">
                        @foreach (var sub in cat.SubMenu)
                        {
                            <li>
                                <a href="@Url.Action("Articles", "Content", new { category = sub.Alias })">@sub.Text</a>
                            </li>
                        }
                    </ul>
                }
            </li>
        }
    </ul>
</div>

reshim.web/Views/Shared/Partials/_MenuLessons.cshtml
@model List<reshim.model.view.ViewModels.Content.MenuItemModel>
<div class="wrapper-nav">
    <ul>
        <li class="first">Категории</li>
        @foreach (var cat in Model)
        {
            <li class="@(cat.SubMenu != null && cat.SubMenu.Any() ? "isSubCategories" : "")">
                <a href="@Url.Action("Lessons", "Content", new { category = cat.Alias })" class="@(cat.SubMenu != null && cat.SubMenu.Any() ? "enable-icon" : "")">@cat.Text</a>
                @if (cat.SubMenu != null && cat.SubMenu.Any())
                {
                    <ul class="subCategories">
                        @foreach (var sub in cat.SubMenu)
                        {
                            <li>
                                <a href="@Url.Action("Lessons", "Content", new { category = sub.Alias })">@sub.Text</a>
                            </li>
                        }
                    </ul>
                }
            </li>
        }
    </ul>
</div>

reshim.web/Views/Shared/Partials/_News.cshtml
@model reshim.model.view.ViewModels.Content.News.NewsViewModel

<div class="block-new clearfix">
    <div class="title-block-new">
        <div class="date-new">@Model.DayCreate<br>@Model.MonthCreate</div>
        <div class="title-new"><a href="@Url.Action("News", "Content", new { alias = Model.Alias })">@Model.Name</a></div>
    </div>
    <div class="content-new">@Html.Raw(Model.Preview)<a class="more" href="@Url.Action("News", "Content", new { alias = Model.Alias })">Подробнее</a></div>
</div>

reshim.web/Views/Shared/Partials/_OrderForm.cshtml
@model reshim.model.view.ViewModels.Task.CreateTaskFormModel

<script src="/Scripts/action/action.order.js" type="text/javascript"></script>

<form class="order" id="quick-order" action="api/task" novalidate="">
    <h3>Узнай стоимость написания твоей работы</h3>
    <fieldset>
        <label>Условие задачи*:</label>
        <div data-role="file-input"></div>
        <div class="note">
            Не более 15Мб (gif, jpg, png, doc, docx, rar, zip).
            <div id="ProgressUploadTask" class="progress-bar" data-role="progress-bar" data-value="0"></div>
        </div>
    </fieldset>

    <fieldset>
        <label>Тип работы*:</label>
        <div class="input-control select">
            <select class="typeWorks custom-select2" name="typeWork" data-placeholder="Выберите тип работы">
                <option value="">Выберите тип работы</option>
                @foreach (var typeWork in Model.TypeWorks)
                {
                    <option value="@typeWork.Id">@typeWork.Name</option>
                }
            </select>
        </div>
        <div class="note">Нет нужного типа работы? Выберите "Другое", а нужный тип укажите в комментарии.</div>
    </fieldset>

    <fieldset>
        <label>Предмет*:</label>
        <div class="input-control select">
            <select class="subjects custom-select2" name="subject" data-placeholder="Выберите предмет">
                <option value="">Выберите предмет</option>
                @foreach (var subject in Model.Subjects)
                {
                    <option value="@subject.Id">@subject.Name</option>
                }
            </select>
        </div>
        <div class="note">Нет нужного предмета? Выберите "Разное", а нужный предмет и раздел укажите в комментарии.</div>
    </fieldset>

    <fieldset>
        <label>Срок сдачи:</label>
        <div class="input-control text datatimeorder" data-role="datepicker">
            <input name="datatimeorder" type="text">
            <input class="calendar btn-date" type="submit" value="">
        </div>
        <div class="note">Указан стандартный срок 3 дня. Укажите нужный Вам!</div>
    </fieldset>

    <fieldset>
        <label>Комментарии:</label>
        <div class="input-control textarea">
            <textarea name="comment" placeholder='Введите комментарий'></textarea>
        </div>
        <div class="note">В комментарии, как и в тексте заказа, оставлять контактные данные запрещено!</div>
    </fieldset>

    @if (!User.Identity.IsAuthenticated)
    {
        <fieldset class="radio-button">
            <label>Уведомление о стоимости работы:</label>
            <div class="input-control radio">
                <label>
                    <input type='radio' name='notify' value='email' id="NotifyEmail" />
                    <span class='check'></span>
                    <span>на email</span>
                </label>
                <label>
                    <input type='radio' name='notify' value='vk' id="NotifyVk" />
                    <span class='check'></span>
                    <span>Вконтакте</span>
                </label>
            </div>
            <div class="note">Выберите способ уведомления о стоимости Вашего заказа!</div>
        </fieldset>
    }

    <div class="quick-reg">
        <h2>Быстрая регистрация</h2>
        <fieldset>
            <label>Email:</label>
            <div class="input-control text">
                <input name="email" type="text" placeholder='Введите email'>
            </div>
            <div class="note">
            </div>
        </fieldset>

        <fieldset>
            <label>Логин:</label>
            <div class="input-control text">
                <input name="login" type="text" placeholder='Введите логин'>
            </div>
            <div class="note">
            </div>
        </fieldset>

        <fieldset>
            <label>Пароль:</label>
            <div class="input-control text">
                <input name="password" type="password" id="password" placeholder='Введите пароль'>
            </div>
            <div class="note">
            </div>
        </fieldset>

        <fieldset>
            <label>Повтор пароля:</label>
            <div class="input-control text">
                <input name="confirmpassword" type="password" placeholder='Повторите пароль'>
            </div>
            <div class="note">
            </div>
        </fieldset>
    </div>

    <button id="SendOrder" class="green">Узнать стоимость</button>
</form>

reshim.web/Views/Shared/Partials/_SidebarTypeWork.cshtml
@model List<reshim.model.view.ViewModels.Content.MenuItemModel>
    
@foreach (var menuItem in Model)
{
    <li class="@(menuItem.Selected ? "active" : "")"><a href="/@menuItem.Alias">@menuItem.Text</a></li>
}

reshim.web/Views/Shared/Partials/_SocialNetworks.cshtml
@using reshim.web.Helpers
<div class="column3 social-networks">
    <p>Мы в социальных сетях:</p>
    <a href="https://twitter.com/iharpeshka" target="_blank">@SVGHelper.TwitterICO()</a>
    <a href="https://vk.com/reshim_net" target="_blank">@SVGHelper.VkICO()</a>
</div>

reshim.web/Views/Shared/Partials/_Statastics.cshtml
@model reshim.model.view.ViewModels.Home.StatisticsSystemViewModel




@*<div class="statistics">
    <p>Пользователей в системе: <b>@Model.CountUsers</b></p>
    <p>Задач в системе: <b>@Model.CountTasks</b></p>
    <p>Решенных задач: <b>@Model.CountComplitedTasks</b></p>
    <p>Последний зарегистрированный пользователь: <b>@Html.ActionLink(@Model.LastRegisterUser.Login, "Index", "User", new { @area = "", @id = @Model.LastRegisterUser.UserId }, null)</b></p>
    <p><b>@Model.OnlineUsers.Count</b> пользователей online:</p>
    @foreach (var user in Model.OnlineUsers)
    {
        <span><b>@Html.ActionLink(user.Login, "Index", "User", new { @area = "", @id = user.UserId }, null)</b></span>
    }
</div>*@

reshim.web/Views/Shared/Partials/_Task.cshtml
@using reshim.web.Helpers
@model reshim.model.view.ViewModels.Task.TaskViewModel

<div class="task clearfix">
    <div class="text">
        <p>
            <b>Предмет:</b> @Model.Subject.Name
        </p>
    </div>
    <div class="time-execute">
        @Html.TextWithIco(SVGHelper.СlockICO(),
            string.Format("<b>Срок:</b> {0} дня", Math.Round((Model.DateOfExecution - Model.DateCreated).TotalDays)),
            colorIco: "blue", colorText: "gray20", htmlAttributes: new { @class = "size_16" })
    </div>
    <div class="price">
        <p>
            <b>Цена:</b> @Model.FormatCost
        </p>
    </div>
</div>

reshim.web/Views/Shared/Partials/_TypeWorks.cshtml
@using reshim.web.Helpers
@model IEnumerable<reshim.model.view.ViewModels.Content.TypeWork.TypeWorkViewModel>

<div class="wrapper">
    <div class="typeWorks">
        <div class="typeWork clearfix">
            <div class="text">
                @Html.TextWithIco(SVGHelper.SubjectICO(), "<b>Предмет</b>", colorIco: "gray90", colorText: "gray20", htmlAttributes: new { @class = "size_20" })
            </div>
            <div class="time-execute">
                @Html.TextWithIco(SVGHelper.СlockICO(), "<b>Срок выполнения</b>", colorIco: "gray90", colorText: "gray20", htmlAttributes: new { @class = "size_20" })
            </div>
            <div class="price">
                @Html.TextWithIco(SVGHelper.CartICO(), "<b>Цена</b>", colorIco: "gray90", colorText: "gray20", htmlAttributes: new { @class = "size_20" })
            </div>
            <div class="btnOrder">
            </div>
        </div>
        @foreach (var typeWork in Model)
        {
            @Html.Partial("Partials/_TypeWork", typeWork)
        }
    </div>
    <a href="#" class="btn green all-typeWorks">@Html.TextWithIco(SVGHelper.CircleDownICO(), "Все выполняемые работы", htmlAttributes: new { @class = "size_20 all-execution-tasks" })</a>
</div>

reshim.web/Views/Shared/Partials/_YandexMetrica.cshtml
<!-- Yandex.Metrika informer -->
<a href="https://metrika.yandex.ru/stat/?id=26826300&amp;from=informer"
   target="_blank" rel="nofollow">
    <img src="//informer.yandex.ru/informer/26826300/3_0_FFFFFFFF_FFFFFFFF_0_pageviews"
         style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" onclick="try{Ya.Metrika.informer({i:this,id:26826300,lang:'ru'});return false}catch(e){}" />
</a>
<!-- /Yandex.Metrika informer -->
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function () {
            try {
                w.yaCounter26826300 = new Ya.Metrika({
                    id: 26826300,
                    webvisor: true,
                    clickmap: true,
                    trackLinks: true,
                    accurateTrackBounce: true,
                    trackHash: true
                });
            } catch (e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/26826300" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->